### ISSUE TITLE
auth() failed! check refresh_token.

### ISSUE THREAD

**Issue by ninwasou** [upbit/pixivpy#12]
Hi, I've got error when trying the example:

Traceback (most recent call last):
  File "test_pixivpy.py", line 21, in <module>
    api.auth()
  File "/usr/local/lib/python2.7/dist-packages/pixivpy3/api.py", line 88, in auth
    raise PixivError('[ERROR] auth() failed! check refresh_token.\nHTTP %s: %s' % (r.status_code, r.text), header=r.headers, body=r.text)
pixivpy3.utils.PixivError: [ERROR] auth() failed! check refresh_token.
HTTP 400: {"has_error":true,"errors":{"system":{"message":"Invalid refresh token","code":1508}}}

What is the problem?

**Comment by upbit** [comment]
En, may be Pixiv change the refresh_token auth method, so re-login with refresh_token is failed.

I will check the new client refresh_token auth, currently you can use **password auth** instead of get access_token by refresh_token. For demo.py, just commented out [this line](https://github.com/upbit/pixivpy/blob/d0b857cf86d5ded290d16d94854690286ad8c0bf/demo.py#L183)

**Comment by grawity** [comment]
According to https://github.com/alphasp/pixiv-api-client/commit/8fa9c7199016f95988e60ad45490b20bfe9bb3c9, refresh_token can be used with a different client ID:

https://github.com/alphasp/pixiv-api-client/blob/8fa9c7199016f95988e60ad45490b20bfe9bb3c9/index.js#L9-L10

**Comment by kaecy** [comment]
grawity is right. it works with those client_id and client_secrets.

**Comment by Hitechcomputergeek** [comment]
You should be able to close this now that https://github.com/upbit/pixivpy/pull/50 has been merged.
