### ISSUE TITLE
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

### ISSUE THREAD

**Issue by sola97** [upbit/pixivpy#14]
前几天还能用的..今天拿出来运行就报错了..
`Traceback (most recent call last):
  File "C:\Users\anime\AppData\Local\Programs\Python\Python35\lib\site-packages\requests-2.9.1-py3.5.egg\requests\packages\urllib3\connectionpool.py", line 554, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\anime\AppData\Local\Programs\Python\Python35\lib\site-packages\requests-2.9.1-py3.5.egg\requests\packages\urllib3\connectionpool.py", line 750, in _prepare_proxy
    conn.connect()
  File "C:\Users\anime\AppData\Local\Programs\Python\Python35\lib\site-packages\requests-2.9.1-py3.5.egg\requests\packages\urllib3\connection.py", line 252, in connect
    ssl_version=resolved_ssl_version)
  File "C:\Users\anime\AppData\Local\Programs\Python\Python35\lib\site-packages\requests-2.9.1-py3.5.egg\requests\packages\urllib3\util\ssl_.py", line 305, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\anime\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 376, in wrap_socket
    _context=self)
  File "C:\Users\anime\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 747, in __init__
    self.do_handshake()
  File "C:\Users\anime\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\anime\AppData\Local\Programs\Python\Python35\lib\ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)`

**Comment by upbit** [comment]
能提供下你的具体调用代码吗？另外你是否设置过代理？

demo.py
~~~python
_REQUESTS_KWARGS = {
  # 'proxies': {
  #   'https': 'http://127.0.0.1:8888',
  # },
  'verify': False,       # PAPI use https, an easy way is disable requests SSL verify
}
~~~

设置的话务必开启requests的verify=False，不然会报SSL证书错误

**Comment by sola97** [comment]
好了，是IE的全局代理忘记关了

**Comment by upbit** [comment]
好的:smile: 如果想走代理，可以像demo里关掉requests的证书校验
有任何疑问或问题，欢迎随时提issues
