### ISSUE TITLE
demo ByPassSniApi  错误

### ISSUE THREAD

**Issue by qihua** [upbit/pixivpy#148]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 444, in wrap_socket
    cnx.do_handshake()
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 815, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 450, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='app-api.pixiv.net.cdn.cloudflare.net.', port=443): Max retries exceeded with url: /auth/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jerry/PycharmProjects/pixivpy/pixivpy3/api.py", line 59, in requests_call
    **self.requests_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests_toolbelt/adapters/host_header_ssl.py", line 43, in send
    return super(HostHeaderSSLAdapter, self).send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='app-api.pixiv.net.cdn.cloudflare.net.', port=443): Max retries exceeded with url: /auth/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jerry/PycharmProjects/pixivpy/example_bypass_sni.py", line 37, in <module>
    main()
  File "/Users/jerry/PycharmProjects/pixivpy/example_bypass_sni.py", line 27, in main
    api.login(_USERNAME, _PASSWORD)
  File "/Users/jerry/PycharmProjects/pixivpy/pixivpy3/api.py", line 73, in login
    return self.auth(username=username, password=password)
  File "/Users/jerry/PycharmProjects/pixivpy/pixivpy3/api.py", line 109, in auth
    r = self.requests_call('POST', url, headers=headers, data=data)
  File "/Users/jerry/PycharmProjects/pixivpy/pixivpy3/api.py", line 64, in requests_call
    raise PixivError('requests %s %s error: %s' % (method, url, e))
pixivpy3.utils.PixivError: requests POST https://app-api.pixiv.net.cdn.cloudflare.net./auth/token error: HTTPSConnectionPool(host='app-api.pixiv.net.cdn.cloudflare.net.', port=443): Max retries exceeded with url: /auth/token (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')])")))

**Comment by upbit** [comment]
Emm, `bad handshake` it means that the SSL handshake failed.
Check if the OpenSSL version of your Py3 is correct, or use Python2 to see if there are still such errors.

**Comment by qihua** [comment]
@upbit 谢谢，，ip 换成210.140.131.219就Ok 了
