### ISSUE TITLE
PixivBot中调用登录报错104

### ISSUE THREAD

**Issue by monokuma233** [upbit/pixivpy#149]
使用ssttkkl/PixivBot部署机器人，依赖3.5.10版本，登录一直报104错误：

Traceback (most recent call last):
  File "/home/pixivbot/PixivBot-0.2.0/pixiv/pixiv_api.py", line 35, in watchman
    await launch(auth)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pixivbot/PixivBot-0.2.0/pixiv/pixiv_api.py", line 27, in auth
    papi.login(settings["pixiv"]["username"], settings["pixiv"]["password"])
  File "/home/pixivbot/.local/lib/python3.9/site-packages/pixivpy3/api.py", line 75, in login
    return self.auth(username=username, password=password)
  File "/home/pixivbot/.local/lib/python3.9/site-packages/pixivpy3/api.py", line 111, in auth
    r = self.requests_call('POST', url, headers=headers, data=data)
  File "/home/pixivbot/.local/lib/python3.9/site-packages/pixivpy3/api.py", line 66, in requests_call
    raise PixivError('requests %s %s error: %s' % (method, url, e))
pixivpy3.utils.PixivError: requests POST https://app-api.pixiv.net.cdn.cloudflare.net./auth/token error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

求解决，感谢！

**Comment by upbit** [comment]
`requests POST https://app-api.pixiv.net.cdn.cloudflare.net./auth/token error`

解析到cloudflare域名了，参考 #138 的那个问题。可以先排除下OpenSSL的版本问题，如果不是可以按 https://github.com/upbit/pixivpy/issues/138#issuecomment-706645066 的方法试试更换Host

dup of #148

**Comment by monokuma233** [comment]
> `requests POST https://app-api.pixiv.net.cdn.cloudflare.net./auth/token error`
> 
> 解析到cloudflare域名了，参考 #138 的那个问题。可以先排除下OpenSSL的版本问题，如果不是可以按 [#138 (comment)](https://github.com/upbit/pixivpy/issues/138#issuecomment-706645066) 的方法试试更换Host
> 
> dup of #138, #148

已解决，十分感谢！

**Comment by monokuma233** [comment]
papi = ByPassSniApi(proxies=proxies)
papi.require_appapi_hosts(hostname="public-api.secure.pixiv.net")
改成这样就OK了。
