### ISSUE TITLE
api.me_feeds: 'JsonDict' object has no attribute 'ref_user'

### ISSUE THREAD

**Issue by upbit** [upbit/pixivpy#15]
API me_feeds() response was changed while Pixiv release iOS 6.x API (app-api), it [broken the CI](https://travis-ci.org/upbit/pixivpy/jobs/143927194):

~~~py
    json_result = api.me_feeds(show_r18=0)
    work = json_result.response[0].ref_user.works[0]
~~~

~~~
Traceback (most recent call last):
  File "demo.py", line 197, in <module>
    main()
  File "demo.py", line 185, in main
    papi_me(api)
  File "demo.py", line 60, in papi_me
    work = json_result.response[0].ref_user.works[0]
  File "/home/travis/build/upbit/pixivpy/pixivpy3/utils.py", line 24, in __getattr__
    raise AttributeError(r"'JsonDict' object has no attribute '%s'" % attr)
AttributeError: 'JsonDict' object has no attribute 'ref_user'
~~~

**Comment by upbit** [comment]
~~~
GET https://app-api.pixiv.net/v1/illust/recommended?content_type=illust&filter=for_ios&include_ranking_label=true

{
    "illusts": [
        {
            "id": 33398960, 
            "title": "美遊さん　（ロリムズイ", 
            "type": "illust", 
            "image_urls": {
                "square_medium": "https://i.pximg.net/c/360x360_70/img-master/img/2013/02/07/21/06/42/33398960_p0_square1200.jpg", 
                "medium": "https://i.pximg.net/c/540x540_70/img-master/img/2013/02/07/21/06/42/33398960_p0_master1200.jpg", 
                "large": "https://i.pximg.net/c/600x1200_90/img-master/img/2013/02/07/21/06/42/33398960_p0_master1200.jpg"
            }, 
            "caption": "意識して顔を大きく手足を細くしてみた小学生っぽくなったかな？　・・・難しいぜ貧乳！難しいぜロリ！", 
            "restrict": 0, 
            "user": {
                "id": 2031777, 
                "name": "ワンツーパンチ!!", 
                "account": "10293847qaz", 
                "profile_image_urls": {
                    "medium": "https://i1.pixiv.net/img55/profile/10293847qaz/7135918.jpg"
                }, 
                "is_followed": false
            }, 
            "tags": [
                {
                    "name": "プリズマ☆イリヤ"
                }, 
                {
                    "name": "美遊"
                }, 
                {
                    "name": "絵チャ"
                }, 
                {
                    "name": "美遊・エーデルフェルト"
                }, 
                {
                    "name": "TKBえろい"
                }, 
                {
                    "name": "プリズマ☆イリヤ100users入り"
                }
            ], 
            "tools": [
                "AzPainter"
            ], 
            "create_date": "2013-02-07T21:06:42+09:00", 
            "page_count": 1, 
            "width": 500, 
            "height": 570, 
            "sanity_level": 6, 
            "meta_single_page": {
                "original_image_url": "https://i1.pixiv.net/img-original/img/2013/02/07/21/06/42/33398960_p0.jpg"
            }, 
            "meta_pages": [ ], 
            "total_view": 6038, 
            "total_bookmarks": 169, 
            "is_bookmarked": false, 
            "visible": true
        }
    }
}
~~~

iOS 6.0 request a new [recommended timeline](https://github.com/upbit/pixivpy/wiki/Sniffer-for-iOS-6.x---Home-Tab#%E4%B8%BA%E4%BD%A0%E6%8E%A8%E8%8D%90), the `me_feeds()` migrate to app-api interface `AppPixivAPI().illust_recommended()`
