### ISSUE TITLE
调用api.download()时连接超时

### ISSUE THREAD

**Issue by pmj110119** [upbit/pixivpy#156]
api.illust_ranking()正常，但加了api.download()就连接超时了。请问这可能是什么原因呢？
`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\qq\lib\site-packages\urllib3\connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\ProgramData\Anaconda3\envs\qq\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\envs\qq\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。`

**Comment by upbit** [comment]
是用的ByPass还是挂的代理？

**Comment by pmj110119** [comment]
之前时bypass+代理
现在把代理关了
`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\qq\lib\site-packages\urllib3\connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\ProgramData\Anaconda3\envs\qq\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\envs\qq\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。`

**Comment by upbit** [comment]
首先，ByPass方法不能作用于download，download是直接访问P站的CDN url:
https://github.com/upbit/pixivpy/blob/master/pixivpy3/api.py#L134

挂代理应该是有效的，可以把作品的URL打印下，用浏览器+`Referer: https://app-api.pixiv.net/`请求看看（代理下）
如果这样也无法访问，基本就可以说明代理到图片的CDN不通

另外，如果浏览器可以但API还是不可访问，这个 Referer 可能要调整下：
`api.download(..., referer="新referer")`
