### ISSUE TITLE
Failed to authenticate to Pixiv; Invalid grant_type parameter

### ISSUE THREAD

**Issue by FujiMakoto** [upbit/pixivpy#168]
Ever since updating my accounts username/password, I've been unable to authenticate to Pixiv with PixivPy.

I've tried changing my username a second time, shortening the password, and so on, but I'm still no longer able to authenticate no matter what I do.

I am certain the username and password being supplied are correct, but it is still returning this error:
```
May 02 01:32:48 taiga python[7700]: [2021-05-02 01:32:48] ERROR: [PIXIV] Failed to authenticate to Pixiv
May 02 01:32:48 taiga python[7700]: Traceback (most recent call last):
May 02 01:32:48 taiga python[7700]:   File "/home/saucenao/twitter-saucenao/twsaucenao/pixiv.py", line 33, in _login
May 02 01:32:48 taiga python[7700]:     self._pixiv.login(self.username, self._password)
May 02 01:32:48 taiga python[7700]:   File "/home/saucenao/twitter-saucenao/venv/lib/python3.7/site-packages/pixivpy3/api.py", line 75, in login
May 02 01:32:48 taiga python[7700]:     return self.auth(username=username, password=password)
May 02 01:32:48 taiga python[7700]:   File "/home/saucenao/twitter-saucenao/venv/lib/python3.7/site-packages/pixivpy3/api.py", line 116, in auth
May 02 01:32:48 taiga python[7700]:     header=r.headers, body=r.text)
May 02 01:32:48 taiga python[7700]: pixivpy3.utils.PixivError: [ERROR] auth() failed! check username and password.
May 02 01:32:48 taiga python[7700]: HTTP 400: {"has_error":true,"errors":{"system":{"message":"Invalid grant_type parameter or parameter missing","code":1508}},"error":"invalid_grant"}
```

**Comment by Xdynix** [comment]
#158

**Comment by FujiMakoto** [comment]
Got it; updated and seems to be working now.
