### ISSUE TITLE
error downloading title with special symbols

### ISSUE THREAD

**Issue by korosu** [upbit/pixivpy#36]
Traceback (most recent call last):
  File "C:\Users\\Desktop\pixivpy-master\download_illusts.py", line 43, in <module>
    main()
  File "C:\Users\\Desktop\pixivpy-master\download_illusts.py", line 40, in main
    aapi.download(image_url, path=directory, name=name)
  File "C:\Users\\Desktop\pixivpy-master\pixivpy3\api.py", line 115, in download
    with open(img_path, 'wb') as out_file:
OSError: [Errno 22] Invalid argument: 'dl\\illust_id_58166861_Pokemon Go?.jpg'

偶尔会有一些带这些符号\ /:*?"<>|的标题出现而导致下载失败
然后为一小部分放弃使用标题文件名又不舍得

**Comment by korosu** [comment]
我傻了 正则表达式轻松搞定的事。。。乱捏了个
name = "illust_id_%d_%s%s" % (illust.id, re.sub("[\s\:\\\*\?\"\<\>\/\|]","",illust.title), extension)
