### ISSUE TITLE
KeyError: 'illust'

### ISSUE THREAD

**Issue by ThyrixYang** [upbit/pixivpy#42]
我在跑第一个example的时候出现了以下错误：
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pixivpy3/utils.py", line 22, in __getattr__
    return self[attr]
KeyError: 'illust'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pixivpy.py", line 19, in <module>
    illust = json_result.illust
  File "/usr/local/lib/python3.5/dist-packages/pixivpy3/utils.py", line 24, in __getattr__
    raise AttributeError(r"'JsonDict' object has no attribute '%s'" % attr)
AttributeError: 'JsonDict' object has no attribute 'illust'
```
请问这个大概是啥原因呢？

我输出了一下json_result.values()
```
dict_values([{'user_message': '', 'message': 'Error occurred at the OAuth process. Please check your Access Token to fix this. Error Message: invalid_request', 'user_message_details': {}, 'reason': ''}])
```

**Comment by upbit** [comment]
具体是哪个API返回的呢？错误里已经有提示，OAuth参数无效。
```
Error occurred at the OAuth process. Please check your Access Token to fix this
```
建议检查下：
1. 是否请求了需要鉴权的接口，而没有开启 `req_auth=True`；
2, 用户名密码是否错误；

**Comment by ThyrixYang** [comment]
哦，我把illust_detail加权限就好了，但是help上说这个不要权限。。。
谢谢

**Comment by upbit** [comment]
`illust_detail()`最近行为有些调整，以前非R-18是可以访问到的
这个等验证一段时间，如果一直这样我再调整下auth参数默认值
