### ISSUE TITLE
PAPI login failed

### ISSUE THREAD

**Issue by Xdynix** [upbit/pixivpy#89]
```python
>>> from pixivpy3 import PixivAPI
>>> api = PixivAPI()
>>> api.login(email, password)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\pixivpy3\api.py", line 76, in login
    return self.auth(username=username, password=password)
  File "C:\Python37\lib\site-packages\pixivpy3\api.py", line 90, in auth
    if self.hosts == "https://app-api.pixiv.net":
AttributeError: 'PixivAPI' object has no attribute 'hosts'
>>> import pixivpy3
>>> pixivpy3.__version__
'3.5.0'
```

**Comment by upbit** [comment]
Sorry for the late reply, please update to 3.5.1 to resolve this issue.
